---
title: "Clinical Analysis of SSNMF"
---
Through careful analysis of our derived data and published clinical trial results, we observed associations between drug sensitivity and the relevance of cancer biomarkers produced in the comodules. Given cancer's aggressive and variable response across patients, identifying these biomarkers is crucial for informing treatment decisions by physicians. By refining a broader dataset of cell lines, physicians can make more informed prognostic plans that are tailored to each  individual cancer type. Given the randomness of genetic variations in cancers across and within organs, correlations between biomarkers and drug sensitivity offers broader insights into how cancer cells are likely to respond to treatment.
	In comodule 1, a strong correlation between the use of cancer biomarkers TP53 and the RAB25 mRNA expression is observed. Both p53 and RAB 25 have served as prognostic biomarkers in literature, with p53 being one of the most common cancer mutations (1,2). Moreover, all drugs in this comodule have mechanisms of action involved in halting the progression of DNA replication and cell communication from the chromosome to the cytoplasm of the cell. (3,4,5,6,7) Table3.4 - Image? 
Moreover, 16 mutations were observed in comodule 2. All mutations were used in literature as biomarkers for diagnosis, treatment sensitivity, tumor progression and prognosis (7). Moreover these mutations encode proteins which will serve in DNA replication and cell communication. Saracatinib halts communication in the cell, while topotecan halts dna replication in the chromosome. Both drugs have been used in literature as a second line treatment in cancer, especially in lung cancer (3,9). Table 3.5
	Furthermore, comodule 21 also contains mutations which give insight to other aspects of a cancer profile of a patient, such as cancer risk, tumor burden, and likelihood of malignancy (10). Both drugs in this comodule have been identified as topoisomerase inhibitors which inhibit the initiation of DNA replication (11,12). These drugs may be used to halt the replication of mutated sequences of RNA present in cancers.  Table 3.6
	In comodule 22, data for mRNA biomarkers along with two mutations are observed. These mRNA biomarkers give indication into diagnosis of cancer severity, drug resistance and sensitivity (13). Furthermore, mutations in the KRAS and Tp53 gene are observed. The mutation in the TP53 gene will inhibit cell death, while a mutation in the kras gene will disrupt proper cell signaling (14,15). This comodule gives insight that is useful for targeted therapy in cancer. All drugs in this comodule also serve to halt all DNA replication and communication in the cell. (3,4,5,7)  Table 3.7
	In comodule 23, a mutation along with a copy number loss is observed. The mutation of TTN is used as a biomarkers for tumor burden analysis (16). Two genes are shown in this commodule as having  copy number losses. They involve olfactory genes OR4M2 and OR4N4. Both of these are biomarkers explain heritable risk in cancer (17). In sum, commodule 23 provides insight into tumor burden and hereditary risk.  Table 3.8
	In comodule 35, copy number loss data may provide insight to sex-linked cancers, treatment progress, and cancer risk in patients(18,19). In this table, the drug TAE684 inhibits cell communication through inhibiting kinase proteins (6). Table 3.9
	Commodule 3 provides information on breast cancer type, and the drug topotecan. In clinical trials, this drug has been used successfully in reducing the amount of cancer cells in breast tissue after first line treatment has failed (21). Comodule 6 referenses the represents lung cancer specifically. In literature, mutations of TTN are used as biomarkers for mutation burden(16), while CSMD3 is stated to be the second most commonly mutated gene in lung cancer (22). Topotecan is approved by the FDA as a second line treatment for lung cancer (23) Table 3.10
	Lastly, comodule 13 provides data for hematopoietic and lymphoid tissue cancers. All drugs in this comodule have been used with some success in clinical trials to treat blood and lymphatic cancers. (6,24,25,26) Table 3.12
 	In sum,These biomarkers provide a treating oncologist with the necessary insights to personalize treatment approaches and improve therapeutic outcomes of patients.  
Bibliography: 
Xiong, J., Li, S., & Zeng, X. (2017). High Rab25 expression associates with Ki67/TP53/CD133/VEGFR expression predicts poor prognosis in gastric cancer. International journal of clinical and experimental pathology, 10(7), 7792–7800. 
Sharma, S., Carlson, S., Gregory-Flores, A., Hinojo-Perez, A., Olson, A., & Thippeswamy, T. (2021). Mechanisms of disease-modifying effect of saracatinib (AZD0530), a Src/Fyn tyrosine kinase inhibitor, in the rat kainate model of temporal lobe epilepsy. Neurobiology of Disease, 156, 105410. https://doi.org/10.1016/j.nbd.2021.105410 
Ramos, R., & Vale, N. (2024). Dual drug repurposing: The example of saracatinib. International Journal of Molecular Sciences, 25(8), 4565. https://doi.org/10.3390/ijms25084565  
Opdam, F. L., Guchelaar, H.-J., Beijnen, J. H., & Schellens, J. H. M. (2012). Lapatinib for advanced or metastatic breast cancer. The Oncologist, 17(4), 536–542. https://doi.org/10.1634/theoncologist.2011-0461​ 
Weber, J. S., Levit, L. A., Adamson, P. C., Bruinooge, S. S., Burris, H. A., Carducci, M. A., Gönen, M., Keefe, S. M., Waterhouse, D. M., Weiner, S. L., & Schuchter, L. M. (2025). The critical role of phase I trials in cancer research and treatment. Journal of Clinical Oncology, 43(5), 123-134. https://doi.org/10.1200/JCO.24.01034​ 
Galkin, A. V., Melnick, J. S., Kim, S., Hood, T. L., Li, N., Li, L., Xia, G., Steensma, R., Chopiuk, G., Jiang, J., & Gray, N. S. (2007). Identification of NVP-TAE684, a potent, selective, and efficacious inhibitor of NPM-ALK. Proceedings of the National Academy of Sciences of the United States of America, 104(1), 270–275. https://doi.org/10.1073/pnas.0609412103​ 
Takahashi, N., Hao, Z., Villaruz, L. C., Zhang, J., Ruiz, J., Petty, W. J., Mamdani, H., Riess, J. W., Nieva, J., Pachecho, J. M., Fuld, A. D., Shum, E., Chauhan, A., Nichols, S., Shimellis, H., McGlone, J., Sciuto, L., Pinkiert, D., Graham, C., Shelat, M., … Thomas, A. (2023). Berzosertib Plus Topotecan vs Topotecan Alone in Patients With Relapsed Small Cell Lung Cancer: A Randomized Clinical Trial. JAMA oncology, 9(12), 1669–1677. https://doi.org/10.1001/jamaoncol.2023.4025 
Asaf, S., Maqsood, F., Jalil, J., Sarfraz, Z., Sarfraz, A., Mustafa, S., & Cherrez Ojeda, I. (2023). Lipocalin 2—not only a biomarker: A study of current literature and systematic findings of ongoing clinical trials. Immunologic Research, 71(3), 287–313. https://doi.org/10.1007/s12026-022-09352-2​ 
Petrelli, F., Ghidini, A., & Luciani, A. (2021). Topotecan or other agents as second-line therapy for relapsed small-cell lung cancer: A meta-analysis of randomized studies. Molecular and Clinical Oncology, 15(4), 218. https://doi.org/10.3892/mco.2021.2383​ 
Bazzichetto, C., Conciatori, F., Pallocca, M., Falcone, I., Fanciulli, M., Cognetti, F., Milella, M., & Ciuffreda, L. (2019). PTEN as a prognostic/predictive biomarker in cancer: An unfulfilled promise? Cancers, 11(4), 435. https://doi.org/10.3390/cancers11040435​ 
Kollmannsberger, C., Mross, K., Jakob, A., Kanz, L., & Bokemeyer, C. (1999). Topotecan—a novel topoisomerase I inhibitor: Pharmacology and clinical experience. Oncology, 56(1), 1–12. https://doi.org/10.1159/000011923​ 
Hasinoff, B. B., Wu, X., Nitiss, J. L., Kanagasabai, R., & Yalowich, J. C. (2012). The anticancer multi-kinase inhibitor dovitinib also targets topoisomerase I and topoisomerase II. Biochemical Pharmacology, 84(12), 1617–1626. https://doi.org/10.1016/j.bcp.2012.09.023​ 
Morgenstern-Kaplan, D., Kareff, S. A., Trabolsi, A., Rodriguez, E., Krause, H., Ribeiro, J. R., Tan, H., Antonarakis, E. S., Lou, E., Nagasaka, M., Algaze, S., Lenz, H.-J., Liu, S. V., Halmos, B., Hoon, D. S. B., Seeber, A., Ma, P. C., El-Deiry, W. S., Vanderwalde, A. M., & Lopes, G. (2024). Genomic, immunologic, and prognostic associations of TROP2 (TACSTD2) expression in solid tumors. The Oncologist, 29(11), e1480–e1491. https://doi.org/10.1093/oncolo/oyae168​ 
McBride, O. W., Merry, D., & Givol, D. (1986). The gene for human p53 cellular tumor antigen is located on chromosome 17 short arm (17p13). Proceedings of the National Academy of Sciences of the United States of America, 83(1), 130–134. https://doi.org/10.1073/pnas.83.1.130​ 
Masjedi, S., Zwiebel, L. J., & Giorgio, T. D. (2019). Olfactory receptor gene abundance in invasive breast carcinoma. Scientific Reports, 9(1), 13736. https://doi.org/10.1038/s41598-019-50085-4​ 
Chen, J., Wen, Y., Su, H., Yu, X., Hong, R., Chen, C., & Su, C. (2022). Deciphering prognostic value of TTN and its correlation with immune infiltration in lung adenocarcinoma. Frontiers in Oncology, 12, 877878. https://doi.org/10.3389/fonc.2022.877878​ 
Masjedi, S., Zwiebel, L. J., & Giorgio, T. D. (2019). Olfactory receptor gene abundance in invasive breast carcinoma. Scientific Reports, 9(1), 13736. https://doi.org/10.1038/s41598-019-50085-4​
 Molnar, C., Heinen, J. P., Reina, J., Llamazares, S., Palumbo, E., Breschi, A., Gay, M., Villarreal, L., Vilaseca, M., Pollarolo, G., & González, C. (2019). The histone code reader PHD finger protein 7 controls sex-linked disparities in gene expression and malignancy in Drosophila. Science Advances, 5(8), eaaw7965. https://doi.org/10.1126/sciadv.aaw7965 
Chaiyawat, P., Phanphaisarn, A., Sirikaew, N., Klangjorhor, J., Thepbundit, V., Teeyakasem, P., Phinyo, P., Pruksakorn, D., & Settakorn, J. (2021). IMPDH2 and HPRT expression and a prognostic significance in preoperative and postoperative patients with osteosarcoma. Scientific Reports, 11(1), 10887. https://doi.org/10.1038/s41598-021-90456-4 
Galkin, A. V., Melnick, J. S., Kim, S., Hood, T. L., Li, N., Li, L., Xia, G., Steensma, R., Chopiuk, G., Jiang, J., & Choi, S. (2007). Identification of NVP-TAE684, a potent, selective, and efficacious inhibitor of NPM-ALK. Proceedings of the National Academy of Sciences of the United States of America, 104(1), 270–275. https://doi.org/10.1073/pnas.0609412103​ 
Jaeckle, K. A., Dixon, J. G., Anderson, S. K., Moreno-Aspitia, A., Colon-Otero, G., Hebenstreit, K., Patel, T. A., Reddy, S. L., & Perez, E. A. (2020). Intra-CSF topotecan in treatment of breast cancer patients with leptomeningeal metastases. Cancer Medicine, 9(21), 7935–7942. https://doi.org/10.1002/cam4.3422​
Liu, P., Morrison, C., Wang, L., Xiong, D., Vedell, P., Cui, P., Hua, X., Ding, F., Lu, Y., James, M., Ebben, J. D., Xu, H., & Adjei, A. A. (2012). Identification of somatic mutations in non-small cell lung carcinomas using whole-exome sequencing. Carcinogenesis, 33(7), 1270–1276. https://doi.org/10.1093/carcin/bgs148​
U.S. Food and Drug Administration. (1998). Hycamtin (topotecan hydrochloride) injection: Drug approval package. https://www.accessdata.fda.gov/drugsatfda_docs/nda/98/20671s004.cfm​ 
Christensen, J. G., Zou, H. Y., Arango, M. E., Li, Q., Lee, J. H., McDonnell, S. R., Yamazaki, S., Alton, G. R., Mroczkowski, B., & Los, G. (2007). Cytoreductive antitumor activity of PF-2341066, a novel inhibitor of anaplastic lymphoma kinase and c-Met, in experimental models of anaplastic large-cell lymphoma. Molecular Cancer Therapeutics, 6(12), 3314–3322. https://doi.org/10.1158/1535-7163.MCT-07-0365
Gambacorti-Passerini, C., Farina, F., Stasia, A., Redaelli, S., Ceccon, M., Mologni, L., Messa, M. C., Guerra, L., Antolini, L., & Piazza, R. G. (2014). Crizotinib in advanced, chemoresistant anaplastic lymphoma kinase–positive lymphoma patients. Journal of the National Cancer Institute, 106(2), djt378. https://doi.org/10.1093/jnci/djt378 
Schäfer, N., Gielen, G. H., Kebir, S., Wieland, A., Till, A., Mack, F., Schaub, C., Tzaridis, T., Reinartz, R., Niessen, M., Fimmers, R., Simon, M., Coch, C., Fuhrmann, C., Herrlinger, U., Scheffler, B., & Glas, M. (2016). Phase I trial of dovitinib (TKI258) in recurrent glioblastoma. Journal of Cancer Research and Clinical Oncology, 142(7), 1581–1589. https://doi.org/10.1007/s00432-016-2161-0 
