---
title: "Math 408 Group Project Proposal"
---
### Group Members: 
*Miles O’Brien* <br>
*Johnathan Harrell* <br>
*Jasmine Wright* <br>
*Kamaran Francis* <br> 
*Steven Li*

### Project Role: 
- **Each member will run Sheena Mogan’s code 20 times** 
- **Johnathan Harrell:** Construct 5 dimensional tensor
- **Rest of team:** work on enabling Sheena Mogan's code to work on GPU

### Group Dynamic Role 
- **Presentation: Johnathan Harrell and Miles O'Brien** 
- **Write-Up: Kamaran Francis, Jasmine Wright, Steven Yi**

# Title: Bio-Marker Discovery by Non-Canonical Polyadic Decomposition

## Purpose: 
Biomarkers are important because it may be possible for scientists to use them to detect, classify, and measure the type of cancer present in a patient. Research is ongoing to support whether or not biomarkers alone are enough to determine cancer types and potential treatments in patients. Patient data can aid in discovering the relationship between specific biomarkers, such as genes that encode proteins. These biomarkers can play an important role in discovering how treatments can be applied to specific cancer types. Our work continues with results obtained in a Master’s thesis by Sheena Mogan titled “Biomarker Discovery by Semi-Supervised Non-Negative Matrix Factorization”. Our goal is to apply Non-Negative Canonical Polyadic Decomposition (NNCPD) to the datasets used in her research and compare our results to her findings. Furthermore, we will confirm the links between the genetic information and cancer types found by NNCPD in the datasets in comparison to the results that have been confirmed in the peer-reviewed publications. We chose NNCPD because of its ability to process multi-omics data tensors, unlike other algorithms limited by their inability to analyze data in more than two dimensions. We hope this method of analyzing genetic oncological data will provide oncologists with a wider lens regarding patient cancer types and possible outcomes of treatment.

## Data: 
The data set we used is from the Cancer Cell Line Encyclopedia and was provided by N. Fujita. It includes 24 cancer types, as well as five types of genetic information and variables for 1054 patients. We use this information to train the algorithm and identify clusters in the biomarker information that ultimately helps us assign a specific cancer type with certain confidence to each subject.

## Variables: 
The variables used in the CCLE data set are listed below, along with their dimensionality and data type.
These variables are:
- Compound Sensitivity <br>
- Mutation <br>
- Copy Number Amplification <br>
- Copy Number Loss <br>
- mRNA Expression <br>
- Tumor Type

## End Product: 
We hope to produce a topic model algorithm that can mirror Sheena Mogan’s and Naoya Fujita’s results that showed Biomarkers can be used to identify Cancer drugs that are able to treat certain types of cancer that have been shown through clinical studies to be difficult to treat either because they return after being treated or metastasis easily in certain parts of the body. Our results eliminate the need to analyze each data frame separately by stacking them into a single tensor before applying Non-negative Canonical Polyadic Decomposition.
$$
```{r}
1+1
```
